// app/layout.js
import ThemeProvider from "./(components)/ThemeProvider";
import "./globals.css";

export const metadata = {
  title: "Chatbot Pro AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
